# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/staging/vault.yml

wordpress_sites:
  spaces:
    site_hosts:
      - canonical: staging.spaces.kisd.de
        # redirects:
        #   - otherdomain.com
    local_path: ../spaces # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:dol-lab/spaces.git # replace with your Git repo URL
    branch: master
    multisite:
      enabled: true
      subdomains: false # Set to true if you're using a subdomain multisite install
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
    env:
      domain_current_site: staging.spaces.kisd.de
      more_composer_dependencies: "{{ more_composer_dependencies }}"
