# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  spaces:
    site_hosts:
      - canonical: spaces.test
        redirects:
          - www.spaces.test
    local_path: ../spaces # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@spaces.test
    multisite:
      enabled: true
      subdomains: false   # Set to true if you're using a subdomain multisite install
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    env:
      domain_current_site: spaces.test
      update_wp_theme_paths: yes
